[package]
name = "iced_gif"
version = "0.1.0"
edition = "2021"
authors = ["tarkah <admin@tarkah.dev>"]
description = "A GIF widget for Iced"
license = "MIT"
repository = "https://github.com/tarkah/iced_gif"

[workspace]
default-members = [
  "./example"
]
members = [
  ".",
  "./example",
]

[dependencies]
iced_native = "0.8"
iced_futures = "0.5"
thiserror = "1.0"

[dependencies.image_rs]
package = "image"
version = "0.24"
features = ["gif"]
