[package]
name = "iced_gif"
version = "0.1.0"
edition = "2021"
authors = ["tarkah <admin@tarkah.dev>"]

[workspace]
default-members = [
  "./example"
]
members = [
  ".",
  "./example",
]

[dependencies]
iced_native = "0.8"
iced_futures = "0.5"

image = { version = "0.24", features = ["gif"] }
thiserror = "1.0"
